location<-setwd("C:\\Users\\elbek\\twoDrive\\Desktop\\UW\\R")
life<-read.csv("data\\data\\dataset - life expectancy\\Life Expectancy Data.csv", header = TRUE)
head(life)
lifePL<-subset(life, Country=="Poland")
lifePLDE<-subset(life, Country=="Germany" | Country=="Poland")
plot(life$Life.expectancy)
plot(lifePL$Life.expectancy)
plot(lifePLDE$Life.expectancy)
plot(x=lifePL$Year, y=lifePL$Life.expectancy)
plot(lifePL$Year, lifePL$Life.expectancy)
plot(x=lifePLDE$Year, y=lifePLDE$Life.expectancy)
plot(x=lifePL$Year, y=lifePL$Life.expectancy, type="l", xlim=c(2000,2012))
plot(x=lifeAFUZ$Year, y=lifeAFUZ$Life.expectancy, main = "Life Expec. in UZB and AfG", col="red")
